version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'idk123'
      POSTGRES_DB: 'diaochan'

  web:
    image: web
    build:
      context: web
      dockerfile: ./Dockerfile
    # env_file:
    #   - web/.env.local
    volumes:
      - ./web:/usr/src/web
    ports:
      - '8080:8080'
    depends_on:
      - server
